name: Build and Deploy

on:
  push:
    branches:
      - add-webpack

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run prod

      - name: Deploy to gh-pages Branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -b gh-pages
          git add -f dist
          git commit -m "Deploy dist to gh-pages branch [skip ci]"
          git push --force "https://$DEPLOY_TOKEN@github.com/as94/whiskey-collection.git" gh-pages
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
